### ISSUE TITLE
Compatibility with cypress?

### ISSUE THREAD

**Issue by lone-cloud** [kwonoj/swc-coverage-instrument#163]
Cypress is a popular testing framework that relies on https://github.com/cypress-io/code-coverage for generating code coverage. That plugin in turn relies on istanbul to do the instrumentation. I noticed that the "coverageVariable" is not being created when the cypress tests are running. I should have the latest version of this plugin configured with my Next.js SWC server. Any idea how to get it working together with cypress code coverage?

**Comment by kwonoj** [comment]
I don't use cypress by myself, so honestly a bit hard to say how does cypress work internally to call transpiler to request to swc to generate instrumentation or even if it's supported usecase.

**Comment by kwonoj** [comment]
Peeking bit, cypress/code-coverage directly uses NYC and all istanbul-related ecosystem only (https://github.com/cypress-io/code-coverage/blob/master/task.js#L210=) and there's no direct way to replace whole transpiler / plugins with customized injection point.

This plugin is somewhat low level to `generate` coverage data compatible as much to istanbul, while it can't be directly drop-in replacement to high level tools if it doesn't support SWC and its pipeline. I saw you filed an upstream issue already, I'd suggest to follow along those if cypress is willing to open up supporting additional coverage instrumentation (and collection, as SWC can't use NYC directly) or other way around.

**Comment by jpierson-at-riis** [comment]
@lone-cloud, follow the instructions for adding and configuring `swc-plugin-coverage-instrument` to your NextJS project and then follow the Cypress parts of the article below. We now have things generally working other than `node_modules` always seem to get instrumented and included in the coverage report.

https://github.com/bahmutov/next-and-cypress-example?tab=readme-ov-file#coverage
