### ISSUE TITLE
Missing export `__transform_plugin_process_impl`

### ISSUE THREAD

**Issue by stahlbauer** [kwonoj/swc-coverage-instrument#166]
### Context

I am trying to use the plugin with the current SWC version for instrumenting a JS code snippet.

The following call is performed:
```
	const pluginOptions = {
		inputSourceMap: sourceMap
	};

	return swc.transformSync(sourceContent, {
		filename: sourceFilename,
		sourceMaps: true,
		inlineSourcesContent: false,
		minify: false,
		isModule: true,
		jsc: {
			experimental: {
				plugins: [['swc-plugin-coverage-instrument', pluginOptions]]
			}
		}
	});
```

### Problem

The call fails with:
```
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("test.js")'

Caused by:
    Missing export __transform_plugin_process_impl

```

**Comment by stahlbauer** [comment]
The invocation of `__transform_plugin_process_impl` was introduced in https://github.com/swc-project/swc/commit/43eeeb35a5ec2a368c3cd215abaff1e1f7fa5a1d

**Comment by stahlbauer** [comment]
The problem seems to be related to https://github.com/swc-project/swc/commit/e8214babf5ad405c7be1f2391a3be01ab355178f

**Comment by stahlbauer** [comment]
There is already a PR that is supposed to fix this: https://github.com/kwonoj/swc-coverage-instrument/pull/165

**Comment by stahlbauer** [comment]
It would be great if there would be information on the required/expected dependencies of this plugin to try it out.

**Comment by kwonoj** [comment]
Since you already found out relavant issue, let me close this and update PR as needed.

As you aware currently there's some rough edges between swc/core host version to the plugins, which I expect to be stablized better with few more changes I am attempt to make in swc/core. Once it's done, picking latest core / plugin would work.
