### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by stahlbauer** [kwonoj/swc-coverage-instrument#167]
I was looking for the license of this project (and was not able to find it). 

Will it also be *Apache 2.0* similar to the `swc` project? It would be great to have some license information for deciding whether or not a project can build on this.

**Thanks** for your great work and the contribution to the open source community :+1:

**Comment by kwonoj** [comment]
There is a license field already: https://github.com/kwonoj/swc-coverage-instrument/blob/main/package.json#L52=

only actual license doc is missing. Will update quickly.

**Comment by stahlbauer** [comment]
Awesome. Thank you :)

**Comment by kwonoj** [comment]
closed via https://github.com/kwonoj/swc-coverage-instrument/pull/165
