### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by chrisapplegate** [kwonoj/swc-coverage-instrument#175]
Thanks for contributing this plugin. When I try running it however, I get a `segmentation fault` trying to instrument a TSX file.

This is my .swcrc:

```
{
  "env": {
    "mode": "entry",
    "coreJs": 3
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "experimental": {
      "plugins": [
        ["swc-plugin-coverage-instrument", {}]
      ]
    }
  }
}
```

I'm running `"@swc/core": "^1.2.247"` and version 0.0.11 of your plugin on an Intel Mac (x64), Node v18.3.

Is your plugin yet compatible with Typescript/React or am I hoping for too much at this early stage?

**Comment by kwonoj** [comment]
No, it should be supported. I guess there was some unexpected changes in the host. Published another version to work with latest @swc/core.
